import { AlertTriangle, CheckCircle2, UserRoundPlus } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { PageHeader } from "../../components/layout/Layouts";
import { EmptyState, LoadingSkeleton, Pagination, TicketCards, TicketFilters, TicketTable } from "../../components/tickets/TicketComponents";
import { filterTickets, sortByPriority } from "../../lib/utils";
import { mockTicketService } from "../../services/ticketService";
import type { FilterState, Ticket } from "../../types";
const initial:FilterState={search:"",status:"all",priority:"all",language:"all",category:"all"};
export function AgentQueuePage({mode="all"}:{mode?:"all"|"high"|"escalated"|"resolved"}){
 const [tickets,setTickets]=useState<Ticket[]>([]);const [loading,setLoading]=useState(true);const [filters,setFilters]=useState(initial);const [selected,setSelected]=useState<string[]>([]);const [page,setPage]=useState(1);const [notice,setNotice]=useState("");
 useEffect(()=>{mockTicketService.getTickets().then(setTickets).finally(()=>setLoading(false))},[]);
 const scoped=useMemo(()=>tickets.filter(t=>mode==="high"?["high","critical"].includes(t.priority.value)||t.category.value.includes("fraud"):mode==="escalated"?t.status==="escalated":mode==="resolved"?["resolved","closed"].includes(t.status):true),[tickets,mode]);
 const filtered=sortByPriority(filterTickets(scoped,filters));const shown=filtered.slice((page-1)*8,page*8);
 const title=mode==="high"?"High-priority review":mode==="escalated"?"Escalated tickets":mode==="resolved"?"Resolved tickets":"Ticket queue";
 return <><PageHeader eyebrow="Support operations" title={title} description={`${filtered.length} tickets · advisory predictions require agent judgement`} actions={<select aria-label="Sort tickets"><option>Priority first</option><option>Newest</option><option>Lowest confidence</option><option>Longest waiting</option></select>}/>{notice&&<div className="success-alert"><CheckCircle2/>{notice}<button onClick={()=>setNotice("")}>Dismiss</button></div>}<div className="card list-card"><TicketFilters filters={filters} onChange={p=>setFilters(v=>({...v,...p}))} onClear={()=>setFilters(initial)}/>{selected.length>0&&<div className="bulk-bar"><strong>{selected.length} selected</strong><button className="btn small" onClick={()=>setNotice(`${selected.length} tickets assigned to Anika Fernando.`)}><UserRoundPlus/>Assign to me</button><button className="btn secondary small" onClick={()=>setNotice(`${selected.length} tickets marked for escalation review.`)}><AlertTriangle/>Escalate</button><button className="link-button" onClick={()=>setSelected([])}>Clear selection</button></div>}{loading?<LoadingSkeleton/>:shown.length===0?<EmptyState detail="No tickets match this queue and filter combination."/>:<><div className="desktop-only"><TicketTable tickets={shown} agent selected={selected} onSelect={id=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}/></div><div className="mobile-list"><TicketCards tickets={shown} agent/></div><div className="table-footer"><span>Showing {shown.length} of {filtered.length} tickets</span><label>Rows per page <select><option>8</option><option>15</option></select></label><Pagination page={page} pages={Math.max(1,Math.ceil(filtered.length/8))} onChange={setPage}/></div></>}</div></>;
}
